package com.bicy.note.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.lerp

/**
 * 主题色预设。每个预设包含亮/暗两套品牌色（主色、辅助色、强调色及各自容器色），
 * 中性色（背景、描边、错误色）由 Color.kt 统一提供，不随预设变化。
 */
data class PresetPalette(
    val primary: Color,
    val onPrimary: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val secondary: Color,
    val onSecondary: Color,
    val secondaryContainer: Color,
    val onSecondaryContainer: Color,
    val tertiary: Color,
    val onTertiary: Color,
    val tertiaryContainer: Color,
    val onTertiaryContainer: Color,
)

data class ThemePreset(
    val id: String,
    val name: String,
    val light: PresetPalette,
    val dark: PresetPalette,
)

private fun preset(
    id: String,
    name: String,
    lightPrimary: Color, lightOnPrimary: Color,
    lightPrimaryContainer: Color, lightOnPrimaryContainer: Color,
    lightSecondary: Color, lightOnSecondary: Color,
    lightSecondaryContainer: Color, lightOnSecondaryContainer: Color,
    lightTertiary: Color, lightOnTertiary: Color,
    lightTertiaryContainer: Color, lightOnTertiaryContainer: Color,
    darkPrimary: Color, darkOnPrimary: Color,
    darkPrimaryContainer: Color, darkOnPrimaryContainer: Color,
    darkSecondary: Color, darkOnSecondary: Color,
    darkSecondaryContainer: Color, darkOnSecondaryContainer: Color,
    darkTertiary: Color, darkOnTertiary: Color,
    darkTertiaryContainer: Color, darkOnTertiaryContainer: Color,
): ThemePreset = ThemePreset(
    id = id,
    name = name,
    light = PresetPalette(
        primary = lightPrimary, onPrimary = lightOnPrimary,
        primaryContainer = lightPrimaryContainer, onPrimaryContainer = lightOnPrimaryContainer,
        secondary = lightSecondary, onSecondary = lightOnSecondary,
        secondaryContainer = lightSecondaryContainer, onSecondaryContainer = lightOnSecondaryContainer,
        tertiary = lightTertiary, onTertiary = lightOnTertiary,
        tertiaryContainer = lightTertiaryContainer, onTertiaryContainer = lightOnTertiaryContainer,
    ),
    dark = PresetPalette(
        primary = darkPrimary, onPrimary = darkOnPrimary,
        primaryContainer = darkPrimaryContainer, onPrimaryContainer = darkOnPrimaryContainer,
        secondary = darkSecondary, onSecondary = darkOnSecondary,
        secondaryContainer = darkSecondaryContainer, onSecondaryContainer = darkOnSecondaryContainer,
        tertiary = darkTertiary, onTertiary = darkOnTertiary,
        tertiaryContainer = darkTertiaryContainer, onTertiaryContainer = darkOnTertiaryContainer,
    ),
)

val ThemePresets: List<ThemePreset> = listOf(
    preset(
        id = "indigo", name = "靛蓝",
        lightPrimary = Color(0xFF5A5CE8), lightOnPrimary = Color(0xFFFFFFFF),
        lightPrimaryContainer = Color(0xFFE0E0FF), lightOnPrimaryContainer = Color(0xFF10105C),
        lightSecondary = Color(0xFF5F5C66), lightOnSecondary = Color(0xFFFFFFFF),
        lightSecondaryContainer = Color(0xFFE7E0EB), lightOnSecondaryContainer = Color(0xFF1C1922),
        lightTertiary = Color(0xFF9A6A45), lightOnTertiary = Color(0xFFFFFFFF),
        lightTertiaryContainer = Color(0xFFFFDBC5), lightOnTertiaryContainer = Color(0xFF361A00),
        darkPrimary = Color(0xFFBFC2FF), darkOnPrimary = Color(0xFF232468),
        darkPrimaryContainer = Color(0xFF4143CF), darkOnPrimaryContainer = Color(0xFFE0E0FF),
        darkSecondary = Color(0xFFCBC4D0), darkOnSecondary = Color(0xFF312E37),
        darkSecondaryContainer = Color(0xFF47444D), darkOnSecondaryContainer = Color(0xFFE7E0EB),
        darkTertiary = Color(0xFFF5B98E), darkOnTertiary = Color(0xFF4A2A0E),
        darkTertiaryContainer = Color(0xFF6A4224), darkOnTertiaryContainer = Color(0xFFFFDBC5),
    ),
    preset(
        id = "emerald", name = "翡翠绿",
        lightPrimary = Color(0xFF006A60), lightOnPrimary = Color(0xFFFFFFFF),
        lightPrimaryContainer = Color(0xFF9EF2E0), lightOnPrimaryContainer = Color(0xFF00201B),
        lightSecondary = Color(0xFF4A635D), lightOnSecondary = Color(0xFFFFFFFF),
        lightSecondaryContainer = Color(0xFFCCE8E1), lightOnSecondaryContainer = Color(0xFF06201B),
        lightTertiary = Color(0xFF456179), lightOnTertiary = Color(0xFFFFFFFF),
        lightTertiaryContainer = Color(0xFFCBE6FF), lightOnTertiaryContainer = Color(0xFF001E31),
        darkPrimary = Color(0xFF82D5C4), darkOnPrimary = Color(0xFF00382F),
        darkPrimaryContainer = Color(0xFF005148), darkOnPrimaryContainer = Color(0xFF9EF2E0),
        darkSecondary = Color(0xFFB1CCC5), darkOnSecondary = Color(0xFF1C3430),
        darkSecondaryContainer = Color(0xFF334B45), darkOnSecondaryContainer = Color(0xFFCCE8E1),
        darkTertiary = Color(0xFFB0CAE8), darkOnTertiary = Color(0xFF0A344C),
        darkTertiaryContainer = Color(0xFF2C4A63), darkOnTertiaryContainer = Color(0xFFCBE6FF),
    ),
    preset(
        id = "ocean", name = "海洋蓝",
        lightPrimary = Color(0xFF0061A4), lightOnPrimary = Color(0xFFFFFFFF),
        lightPrimaryContainer = Color(0xFFD3E4FF), lightOnPrimaryContainer = Color(0xFF001C36),
        lightSecondary = Color(0xFF565F71), lightOnSecondary = Color(0xFFFFFFFF),
        lightSecondaryContainer = Color(0xFFDAE2F9), lightOnSecondaryContainer = Color(0xFF131C2B),
        lightTertiary = Color(0xFF6B5778), lightOnTertiary = Color(0xFFFFFFFF),
        lightTertiaryContainer = Color(0xFFF2DDFE), lightOnTertiaryContainer = Color(0xFF251432),
        darkPrimary = Color(0xFFA6C8FF), darkOnPrimary = Color(0xFF003258),
        darkPrimaryContainer = Color(0xFF00497D), darkOnPrimaryContainer = Color(0xFFD3E4FF),
        darkSecondary = Color(0xFFBEC6DC), darkOnSecondary = Color(0xFF283141),
        darkSecondaryContainer = Color(0xFF3E4759), darkOnSecondaryContainer = Color(0xFFDAE2F9),
        darkTertiary = Color(0xFFD8B9E6), darkOnTertiary = Color(0xFF3C2849),
        darkTertiaryContainer = Color(0xFF533F60), darkOnTertiaryContainer = Color(0xFFF2DDFE),
    ),
    preset(
        id = "sakura", name = "樱花粉",
        lightPrimary = Color(0xFFAD3676), lightOnPrimary = Color(0xFFFFFFFF),
        lightPrimaryContainer = Color(0xFFFFD8E7), lightOnPrimaryContainer = Color(0xFF3E001E),
        lightSecondary = Color(0xFF74565F), lightOnSecondary = Color(0xFFFFFFFF),
        lightSecondaryContainer = Color(0xFFFFDAE2), lightOnSecondaryContainer = Color(0xFF2B151C),
        lightTertiary = Color(0xFF7D5636), lightOnTertiary = Color(0xFFFFFFFF),
        lightTertiaryContainer = Color(0xFFFFDCBF), lightOnTertiaryContainer = Color(0xFF2F1600),
        darkPrimary = Color(0xFFFFADCD), darkOnPrimary = Color(0xFF65003A),
        darkPrimaryContainer = Color(0xFF861955), darkOnPrimaryContainer = Color(0xFFFFD8E7),
        darkSecondary = Color(0xFFE5BDC7), darkOnSecondary = Color(0xFF442A32),
        darkSecondaryContainer = Color(0xFF5C4048), darkOnSecondaryContainer = Color(0xFFFFDAE2),
        darkTertiary = Color(0xFFEDBE8F), darkOnTertiary = Color(0xFF48290A),
        darkTertiaryContainer = Color(0xFF633F21), darkOnTertiaryContainer = Color(0xFFFFDCBF),
    ),
    preset(
        id = "sunset", name = "日落橙",
        lightPrimary = Color(0xFF8F4C00), lightOnPrimary = Color(0xFFFFFFFF),
        lightPrimaryContainer = Color(0xFFFFDCBE), lightOnPrimaryContainer = Color(0xFF2E1500),
        lightSecondary = Color(0xFF715A43), lightOnSecondary = Color(0xFFFFFFFF),
        lightSecondaryContainer = Color(0xFFFDDCBD), lightOnSecondaryContainer = Color(0xFF271906),
        lightTertiary = Color(0xFF5B6234), lightOnTertiary = Color(0xFFFFFFFF),
        lightTertiaryContainer = Color(0xFFDFE6A8), lightOnTertiaryContainer = Color(0xFF181E00),
        darkPrimary = Color(0xFFFFB97D), darkOnPrimary = Color(0xFF4A2700),
        darkPrimaryContainer = Color(0xFF6C3900), darkOnPrimaryContainer = Color(0xFFFFDCBE),
        darkSecondary = Color(0xFFE3C0A2), darkOnSecondary = Color(0xFF402B18),
        darkSecondaryContainer = Color(0xFF57412C), darkOnSecondaryContainer = Color(0xFFFDDCBD),
        darkTertiary = Color(0xFFC2C98C), darkOnTertiary = Color(0xFF2D3316),
        darkTertiaryContainer = Color(0xFF434A20), darkOnTertiaryContainer = Color(0xFFDFE6A8),
    ),
    preset(
        id = "violet", name = "罗兰紫",
        lightPrimary = Color(0xFF6750A4), lightOnPrimary = Color(0xFFFFFFFF),
        lightPrimaryContainer = Color(0xFFEADDFF), lightOnPrimaryContainer = Color(0xFF21005D),
        lightSecondary = Color(0xFF625B71), lightOnSecondary = Color(0xFFFFFFFF),
        lightSecondaryContainer = Color(0xFFE8DEF8), lightOnSecondaryContainer = Color(0xFF1E192B),
        lightTertiary = Color(0xFF7D5260), lightOnTertiary = Color(0xFFFFFFFF),
        lightTertiaryContainer = Color(0xFFFFD8E4), lightOnTertiaryContainer = Color(0xFF31111D),
        darkPrimary = Color(0xFFD0BCFF), darkOnPrimary = Color(0xFF381E72),
        darkPrimaryContainer = Color(0xFF4F378B), darkOnPrimaryContainer = Color(0xFFEADDFF),
        darkSecondary = Color(0xFFCCC4DC), darkOnSecondary = Color(0xFF342F40),
        darkSecondaryContainer = Color(0xFF4A4557), darkOnSecondaryContainer = Color(0xFFE8DEF8),
        darkTertiary = Color(0xFFEFB8C8), darkOnTertiary = Color(0xFF4A2532),
        darkTertiaryContainer = Color(0xFF633B48), darkOnTertiaryContainer = Color(0xFFFFD8E4),
    ),
)

fun themePresetById(id: String): ThemePreset =
    ThemePresets.firstOrNull { it.id == id } ?: ThemePresets.first()

private fun PresetPalette.toLightScheme() = lightColorScheme(
    primary = primary,
    onPrimary = onPrimary,
    primaryContainer = primaryContainer,
    onPrimaryContainer = onPrimaryContainer,
    secondary = secondary,
    onSecondary = onSecondary,
    secondaryContainer = secondaryContainer,
    onSecondaryContainer = onSecondaryContainer,
    tertiary = tertiary,
    onTertiary = onTertiary,
    tertiaryContainer = tertiaryContainer,
    onTertiaryContainer = onTertiaryContainer,
    error = Error,
    onError = OnError,
    errorContainer = ErrorContainer,
    onErrorContainer = OnErrorContainer,
    background = LightBackground,
    onBackground = LightOnBackground,
    surface = LightBackground,
    onSurface = LightOnBackground,
    surfaceVariant = lerp(LightSurfaceVariant, primary, 0.10f),
    onSurfaceVariant = LightOnSurfaceVariant,
    outline = LightOutline,
    outlineVariant = LightOutlineVariant,
    surfaceContainerLowest = LightBackground,
    surfaceContainerLow = lerp(LightBackground, primary, 0.05f),
    surfaceContainer = lerp(LightBackground, primary, 0.08f),
    surfaceContainerHigh = lerp(LightBackground, primary, 0.12f),
    surfaceContainerHighest = lerp(LightBackground, primary, 0.16f),
)

private fun PresetPalette.toDarkScheme() = darkColorScheme(
    primary = primary,
    onPrimary = onPrimary,
    primaryContainer = primaryContainer,
    onPrimaryContainer = onPrimaryContainer,
    secondary = secondary,
    onSecondary = onSecondary,
    secondaryContainer = secondaryContainer,
    onSecondaryContainer = onSecondaryContainer,
    tertiary = tertiary,
    onTertiary = onTertiary,
    tertiaryContainer = tertiaryContainer,
    onTertiaryContainer = onTertiaryContainer,
    error = DarkError,
    onError = DarkOnError,
    errorContainer = DarkErrorContainer,
    onErrorContainer = DarkOnErrorContainer,
    background = DarkBackground,
    onBackground = DarkOnBackground,
    surface = DarkBackground,
    onSurface = DarkOnBackground,
    surfaceVariant = lerp(DarkSurfaceVariant, primary, 0.08f),
    onSurfaceVariant = DarkOnSurfaceVariant,
    outline = DarkOutline,
    outlineVariant = DarkOutlineVariant,
    surfaceContainerLowest = DarkBackground,
    surfaceContainerLow = lerp(DarkBackground, primary, 0.06f),
    surfaceContainer = lerp(DarkBackground, primary, 0.10f),
    surfaceContainerHigh = lerp(DarkBackground, primary, 0.14f),
    surfaceContainerHighest = lerp(DarkBackground, primary, 0.18f),
)

fun ThemePreset.lightScheme() = light.toLightScheme()

fun ThemePreset.darkScheme() = dark.toDarkScheme()